/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scheduler_Main */

#ifndef _Included_com_scheduler_Main
#define _Included_com_scheduler_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scheduler_Main
 * Method:    outQueueInit
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_scheduler_Main_outQueueInit
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_scheduler_Main
 * Method:    schedulerInit
 * Signature: (IIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_scheduler_Main_schedulerInit
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     com_scheduler_Main
 * Method:    addTasks
 * Signature: (J[Lcom/scheduler/UserTask;I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_scheduler_Main_addTasks
  (JNIEnv *, jclass, jlong, jobjectArray, jint);

/*
 * Class:     com_scheduler_Main
 * Method:    removeTask
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_scheduler_Main_removeTask
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_scheduler_Main
 * Method:    schedulerRun
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_scheduler_Main_schedulerRun
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_scheduler_Main
 * Method:    schedulerShutdown
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_scheduler_Main_schedulerShutdown
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
